---
- include: repo.yml
  tags: repmgr-repo

- include: install.yml
  tags: repmgr-install

- include: configure.yml
  tags: repmgr-configure

- include: bootstrap.yml
  when:
  - repmgr_bootstrap|bool
  tags: repmgr-bootstrap

- include: cron_jobs.yml
  when: repmgr_cron_status
  tags: repmgr-cron
