---

- name: start repmgrd
  systemd:
    name: repmgrd
    state: started

- name: stop repmgrd
  systemd:
    name: repmgrd
    state: stopped

- name: restart repmgrd
  systemd:
    name: repmgrd
    state: restarted

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
